### ISSUE TITLE
Validation of Unions

### ISSUE THREAD

**Issue by NickG123** [tebeka/fastavro#48]
Hey,
I'm currently running into the following problem:
With a schema like this:

```
protocol test {
  record a {
    int x;
    int y;
  }

  record b {
    int x;
    int y;
    union {null, int} z;
  }

  record test {
    union {a, b} val;
  } 
}
```

I can create a file with two objects:

```
>>> data = StringIO.StringIO()
>>> fastavro.writer(data, schema, [{'val': {'x': 1, 'y': 2}},{'val': {'x': 3, 'y':4, 'z':5}}])
```

However, because of the way unions are validated, both 'val's are serialized as type 'a', and the 'z' field of the second object is silently dropped.

This can be confirmed by reading in the objects:

```
>>> data.seek(0)
>>> reader = fastavro.reader(data)
>>> next(reader)
{u'val': {u'y': 2, u'x': 1}}
>>> next(reader)
{u'val': {u'y': 4, u'x': 3}}
```

Do you have any suggestions for a way of dealing with this problem?

Thanks,
Nick

**Comment by tebeka** [comment]
Thanks for reporting. I'll try to have a look this weekend.

**Comment by scottbelden** [comment]
Someone posted a similar problem with the standard avro library here: https://issues.apache.org/jira/browse/AVRO-1777

Their suggestion was to keep track of the number of matching fields and in the end go with the one that matched the most. It seems pretty reasonable. Alternatively, one could go with a much more strict approach and force the keys in the dictionary to exactly match the fields in the schema, but that would break people that are making the use of the fact that extra data in the dictionary is ignored.

**Comment by tebeka** [comment]
This should be fixed in 0.9.10

**Comment by movermeyer** [comment]
This was not fixed. Tested with fastavro-0.9.11 using the test case from this issue.

**Comment by tebeka** [comment]
Hmm. OK, will check again.
